services:
  # Note: Using external MySQL database, no local DB service needed

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roadtrip-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roadtrip-frontend
    command: ["pnpm", "dev"]
    env_file:
      - .env
    ports:
      - "3500:3500"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3500"]
      interval: 30s
      timeout: 10s
      retries: 3

  graphhopper:
    build:
      context: ./infrastructure/graphhopper
      dockerfile: Dockerfile
      args:
        GH_VERSION: "8.0"
    container_name: roadtrip-graphhopper
    profiles:
      - selfhost
    environment:
      - JAVA_OPTS=-Xmx4g -Xms4g
    ports:
      - "8989:8989"
    volumes:
      - ./data/graphhopper:/data
      - ./infrastructure/graphhopper/config.yml:/data/config.yml
      - ./infrastructure/graphhopper/custom_models:/data/custom_models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/health"]
      interval: 30s
      timeout: 10s
      retries: 10

# No volumes needed for external MySQL database