graphhopper:
  # DataReader file
  datareader.file: /data/map.osm.pbf

  # Local folder used by graphhopper
  graph.location: /data/graph-cache

  # Routing profiles
  profiles:
    - name: car
      vehicle: car
      weighting: custom
      custom_model:
        priority:
          - if: "road_access == DESTINATION"
            multiply_by: 0.5

      turn_costs: true

  # Routing profiles for CH
  profiles_ch:
    - profile: car

  # Routing profiles for LM
  profiles_lm: []

  # Custom models directory (mounted by docker-compose)
  custom_models_directory: /data/custom_models

  # Import settings (GraphHopper 8.x expects dotted keys)
  import.osm.ignored_highways:
    - ferry

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0